source "http://rubygems.org"
gem 'gdbm'
gem 'highline'
gem 'dynamoid'
gem 'fluent-logger'

# need to add JRuby properties for memcache native extention. 
# $ cat ~/.jrubyrc 
# cext.enabled=true
gem 'memcache'
